version: "3.7"
services:
  db:
    image: mysql
    container_name: mysql-container-dp
    command: --default-authentication-plugin=mysql_native_password
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: 321982
      MYSQL_DATABASE: doragonpixel
    ports:
      - "3306:33060"
      - "33060:3306"
    networks:
      - conn_all
    volumes:
     - "./mysql:/var/lib/mysql"

  laravel-api:
    container_name: laravel-api-dp
    build: 
      context: "."
      dockerfile: php.Dockerfile
    ports:
      - "8002:80"
    working_dir: "/var/www/html"
    command: [sh, -c, "sudo chmod -R 775 storage && \
      sudo chown -R $USER:www-data storage && \
      sudo chown -R $USER:www-data bootstrap/cache && \
      composer install && \
      php artisan migrate && \ 
      apachectl -D FOREGROUND"]
    stdin_open: true
    tty: true
    environment:
      - <...>
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./api:/var/www/html"
    networks: 
      - conn_all

  vue:
    build: 
      context: .
      dockerfile: vue.Dockerfile
    container_name: vue-container-dp
    working_dir: "/usr/src"
    command: bash -c "npm install && npm update && npm install @vue/cli && npm run dev"
    stdin_open: true
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3000:3000"
    volumes:
      - "./web:/usr/src"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - YOUR_APP_WEB_HTTP_PORT=8080
    networks:
      - conn_all

networks:
  conn_all: